spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dealer
    username: root
    password: Ilcavalierenero
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
