spring:
  datasource:
    url: jdbc:mysql://localhost:3306/     // <-- modificare con il vostro db
    username: root
    password:                             // <-- modificare con la vostra password
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
